n: 4

qcs:
  - id: 1
    host: 127.0.0.1
    port: 1000
  - id: 2
    host: 127.0.0.1
    port: 1000
  - id: 3
    host: 127.0.0.1
    port: 1000
  - id: 4
    host: 127.0.0.1
    port: 1000
